/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { TimeEntry } from "./TimeEntry";
import { TimeEntryCountArgs } from "./TimeEntryCountArgs";
import { TimeEntryFindManyArgs } from "./TimeEntryFindManyArgs";
import { TimeEntryFindUniqueArgs } from "./TimeEntryFindUniqueArgs";
import { CreateTimeEntryArgs } from "./CreateTimeEntryArgs";
import { UpdateTimeEntryArgs } from "./UpdateTimeEntryArgs";
import { DeleteTimeEntryArgs } from "./DeleteTimeEntryArgs";
import { User } from "../../user/base/User";
import { TimeEntryService } from "../timeEntry.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TimeEntry)
export class TimeEntryResolverBase {
  constructor(
    protected readonly service: TimeEntryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TimeEntry",
    action: "read",
    possession: "any",
  })
  async _timeEntriesMeta(
    @graphql.Args() args: TimeEntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TimeEntry])
  @nestAccessControl.UseRoles({
    resource: "TimeEntry",
    action: "read",
    possession: "any",
  })
  async timeEntries(
    @graphql.Args() args: TimeEntryFindManyArgs
  ): Promise<TimeEntry[]> {
    return this.service.timeEntries(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TimeEntry, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TimeEntry",
    action: "read",
    possession: "own",
  })
  async timeEntry(
    @graphql.Args() args: TimeEntryFindUniqueArgs
  ): Promise<TimeEntry | null> {
    const result = await this.service.timeEntry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TimeEntry)
  @nestAccessControl.UseRoles({
    resource: "TimeEntry",
    action: "create",
    possession: "any",
  })
  async createTimeEntry(
    @graphql.Args() args: CreateTimeEntryArgs
  ): Promise<TimeEntry> {
    return await this.service.createTimeEntry({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => TimeEntry)
  @nestAccessControl.UseRoles({
    resource: "TimeEntry",
    action: "update",
    possession: "any",
  })
  async updateTimeEntry(
    @graphql.Args() args: UpdateTimeEntryArgs
  ): Promise<TimeEntry | null> {
    try {
      return await this.service.updateTimeEntry({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => TimeEntry)
  @nestAccessControl.UseRoles({
    resource: "TimeEntry",
    action: "delete",
    possession: "any",
  })
  async deleteTimeEntry(
    @graphql.Args() args: DeleteTimeEntryArgs
  ): Promise<TimeEntry | null> {
    try {
      return await this.service.deleteTimeEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: TimeEntry): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
